export type CountryTier = "TIER_1" | "TIER_2" | "TIER_3";

export type FundingRound = {
  round: string;
  amount: string;
  amountUsd: number | null;
  announcedOn: string | null;
  investors: string[];
  source: string | null;
};

export type FounderDirectoryItem = {
  id: string;
  slug: string;
  companySlug: string;
  founderName: string;
  companyName: string;
  foundedYear: number | null;
  headquarters: string | null;
  industry: string;
  stage: string;
  productSummary: string;
  fundingInfo: string | null;
  sourceUrl: string;
  ycProfileUrl: string | null;
  websiteUrl: string | null;
  employeeCount: string | null;
  techStack: string[];
  recentNews: string[];
  linkedinUrl: string | null;
  twitterUrl: string | null;
  verified: boolean;
  isFeatured: boolean;
  avatarUrl: string | null;
  country?: string;
  countryTier?: CountryTier;
  fundingTotalDisplay?: string | null;
  fundingTotalUsd?: number | null;
  lastRound?: FundingRound | null;
  allRounds?: FundingRound[];
  isHiring?: boolean;
  hiringRoles?: string[];
};

export type FounderSyncInput = {
  founderName: string;
  companyName: string;
  foundedYear?: number | null;
  headquarters?: string | null;
  industry?: string;
  stage?: string;
  productSummary: string;
  fundingInfo?: string | null;
  sourceUrl?: string;
  ycProfileUrl?: string | null;
  websiteUrl?: string | null;
  employeeCount?: string | null;
  techStack?: string[] | null;
  recentNews?: string[] | null;
  linkedinUrl?: string | null;
  twitterUrl?: string | null;
  verified?: boolean;
  isFeatured?: boolean;
  avatarUrl?: string | null;
  slug?: string;
  country?: string;
  countryTier?: CountryTier;
  fundingTotalDisplay?: string | null;
  fundingTotalUsd?: number | null;
  lastRound?: FundingRound | null;
  allRounds?: FundingRound[] | null;
  isHiring?: boolean;
  hiringRoles?: string[] | null;
};
