export type FounderDirectoryItem = {
  id: string;
  slug: string;
  companySlug: string;
  founderName: string;
  companyName: string;
  foundedYear: number | null;
  headquarters: string | null;
  industry: string;
  stage: string;
  productSummary: string;
  fundingInfo: string | null;
  sourceUrl: string;
  ycProfileUrl: string | null;
  websiteUrl: string | null;
  employeeCount: string | null;
  techStack: string[];
  recentNews: string[];
  linkedinUrl: string | null;
  twitterUrl: string | null;
  verified: boolean;
  isFeatured: boolean;
  avatarUrl: string | null;
};

export type FounderSyncInput = {
  founderName: string;
  companyName: string;
  foundedYear?: number | null;
  headquarters?: string | null;
  industry?: string;
  stage?: string;
  productSummary: string;
  fundingInfo?: string | null;
  sourceUrl?: string;
  ycProfileUrl?: string | null;
  websiteUrl?: string | null;
  employeeCount?: string | null;
  techStack?: string[] | null;
  recentNews?: string[] | null;
  linkedinUrl?: string | null;
  twitterUrl?: string | null;
  verified?: boolean;
  isFeatured?: boolean;
  avatarUrl?: string | null;
  slug?: string;
};
