import type { FounderDirectoryItem } from "@/lib/founders/types";

export const WIKI_SOURCE_URL =
  "https://en.wikipedia.org/wiki/List_of_companies_named_after_people";

export const WIKI_Eponymous_SEED: FounderDirectoryItem[] = [
  {
    id: "ford-motor-henry-ford",
    slug: "ford-motor-henry-ford",
    founderName: "Henry Ford",
    companyName: "Ford Motor Company",
    foundedYear: 1903,
    headquarters: "Dearborn",
    industry: "Automotive",
    stage: "Public",
    productSummary:
      "Global vehicle manufacturer producing consumer and commercial automotive products.",
    fundingInfo: "Publicly listed (NYSE: F).",
    sourceUrl: WIKI_SOURCE_URL,
    ycProfileUrl: "https://www.ycombinator.com/founders?query=Henry+Ford",
    verified: true,
    avatarUrl: null,
  },
  {
    id: "boeing-william-boeing",
    slug: "boeing-william-boeing",
    founderName: "William Boeing",
    companyName: "Boeing",
    foundedYear: 1916,
    headquarters: "Arlington",
    industry: "Aerospace",
    stage: "Public",
    productSummary:
      "Aerospace company building commercial aircraft, defense systems, and space technology.",
    fundingInfo: "Publicly listed (NYSE: BA).",
    sourceUrl: WIKI_SOURCE_URL,
    ycProfileUrl: "https://www.ycombinator.com/founders?query=William+Boeing",
    verified: true,
    avatarUrl: null,
  },
  {
    id: "dell-michael-dell",
    slug: "dell-michael-dell",
    founderName: "Michael Dell",
    companyName: "Dell Technologies",
    foundedYear: 1984,
    headquarters: "Round Rock",
    industry: "Technology",
    stage: "Public",
    productSummary:
      "Enterprise and consumer hardware, infrastructure, and cloud-focused technology products.",
    fundingInfo: "Publicly listed (NYSE: DELL).",
    sourceUrl: WIKI_SOURCE_URL,
    ycProfileUrl: "https://www.ycombinator.com/founders?query=Michael+Dell",
    verified: true,
    avatarUrl: null,
  },
  {
    id: "siemens-werner-von-siemens",
    slug: "siemens-werner-von-siemens",
    founderName: "Werner von Siemens",
    companyName: "Siemens",
    foundedYear: 1847,
    headquarters: "Munich",
    industry: "Industrial",
    stage: "Public",
    productSummary:
      "Industrial automation, infrastructure, and healthcare technology solutions.",
    fundingInfo: "Publicly listed (XETRA: SIE).",
    sourceUrl: WIKI_SOURCE_URL,
    ycProfileUrl: "https://www.ycombinator.com/founders?query=Werner+von+Siemens",
    verified: true,
    avatarUrl: null,
  },
  {
    id: "adidas-adi-dassler",
    slug: "adidas-adi-dassler",
    founderName: "Adi Dassler",
    companyName: "Adidas",
    foundedYear: 1949,
    headquarters: "Herzogenaurach",
    industry: "Consumer",
    stage: "Public",
    productSummary:
      "Global sportswear and footwear brand for athletes and lifestyle consumers.",
    fundingInfo: "Publicly listed (XETRA: ADS).",
    sourceUrl: WIKI_SOURCE_URL,
    ycProfileUrl: "https://www.ycombinator.com/founders?query=Adi+Dassler",
    verified: true,
    avatarUrl: null,
  },
  {
    id: "porsche-ferdinand-porsche",
    slug: "porsche-ferdinand-porsche",
    founderName: "Ferdinand Porsche",
    companyName: "Porsche",
    foundedYear: 1931,
    headquarters: "Stuttgart",
    industry: "Automotive",
    stage: "Public",
    productSummary:
      "Performance and luxury automotive manufacturer with global vehicle lineup.",
    fundingInfo: "Publicly listed (FWB: P911).",
    sourceUrl: WIKI_SOURCE_URL,
    ycProfileUrl: "https://www.ycombinator.com/founders?query=Ferdinand+Porsche",
    verified: true,
    avatarUrl: null,
  },
  {
    id: "suzuki-michio-suzuki",
    slug: "suzuki-michio-suzuki",
    founderName: "Michio Suzuki",
    companyName: "Suzuki",
    foundedYear: 1909,
    headquarters: "Hamamatsu",
    industry: "Automotive",
    stage: "Public",
    productSummary:
      "Automotive and mobility manufacturer with strong compact vehicle presence.",
    fundingInfo: "Publicly listed (TYO: 7269).",
    sourceUrl: WIKI_SOURCE_URL,
    ycProfileUrl: "https://www.ycombinator.com/founders?query=Michio+Suzuki",
    verified: true,
    avatarUrl: null,
  },
  {
    id: "yamaha-torakusu-yamaha",
    slug: "yamaha-torakusu-yamaha",
    founderName: "Torakusu Yamaha",
    companyName: "Yamaha Corporation",
    foundedYear: 1887,
    headquarters: "Hamamatsu",
    industry: "Consumer",
    stage: "Public",
    productSummary:
      "Musical instruments and audio equipment company with global distribution.",
    fundingInfo: "Publicly listed (TYO: 7951).",
    sourceUrl: WIKI_SOURCE_URL,
    ycProfileUrl: "https://www.ycombinator.com/founders?query=Torakusu+Yamaha",
    verified: true,
    avatarUrl: null,
  },
  {
    id: "heinz-henry-j-heinz",
    slug: "heinz-henry-j-heinz",
    founderName: "Henry J. Heinz",
    companyName: "Heinz",
    foundedYear: 1869,
    headquarters: "Pittsburgh",
    industry: "Consumer",
    stage: "Private",
    productSummary:
      "Global packaged foods brand portfolio focused on condiments and meals.",
    fundingInfo: "Part of Kraft Heinz group brands.",
    sourceUrl: WIKI_SOURCE_URL,
    ycProfileUrl: "https://www.ycombinator.com/founders?query=Henry+J.+Heinz",
    verified: true,
    avatarUrl: null,
  },
  {
    id: "tiffany-charles-lewis-tiffany",
    slug: "tiffany-charles-lewis-tiffany",
    founderName: "Charles Lewis Tiffany",
    companyName: "Tiffany & Co.",
    foundedYear: 1837,
    headquarters: "New York City",
    industry: "Luxury",
    stage: "Private",
    productSummary:
      "Luxury jewelry and accessories brand with global retail presence.",
    fundingInfo: "Acquired by LVMH in 2021.",
    sourceUrl: WIKI_SOURCE_URL,
    ycProfileUrl:
      "https://www.ycombinator.com/founders?query=Charles+Lewis+Tiffany",
    verified: true,
    avatarUrl: null,
  },
  {
    id: "ben-jerry-ben-cohen-jerry-greenfield",
    slug: "ben-jerry-ben-cohen-jerry-greenfield",
    founderName: "Ben Cohen & Jerry Greenfield",
    companyName: "Ben & Jerry's",
    foundedYear: 1978,
    headquarters: "South Burlington",
    industry: "Consumer",
    stage: "Private",
    productSummary:
      "Ice cream brand known for premium flavors and social-impact branding.",
    fundingInfo: "Subsidiary of Unilever.",
    sourceUrl: WIKI_SOURCE_URL,
    ycProfileUrl:
      "https://www.ycombinator.com/founders?query=Ben+Cohen+Jerry+Greenfield",
    verified: true,
    avatarUrl: null,
  },
];
